# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da713fd35c8c44e1a0df5ff2f05bdaefecce1f99fa6fe1953a3331c768d315fa35752c61674abb5b1317720c1cbdf030d882a01f65bcc7c4eb3e29f0a7f7e663

test:
  secret_key_base: f6ba75f996b83e43233db3eca8916cd03917d76e0c7a675d864617a4474ec720c5fe72b5e2fe42b65e40caf60e8c5929f9317c583cc328932b4f266969c99bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
